variables:
    {emojichat} = true



on chat:
    if {emojiChat} is true:
        replace all ":)" with "☺" in message
        replace all ":(" with "☹" in message
        replace all "):" with "☹" in message
        replace all "(:" with "☺" in message
        replace all ":skull:" with "☠" in message
        replace all ":kiss:" with "&c💋&f" in message
        replace all ":heart:" with "&c❤&f" in message
        replace all ":mad:" with "&c😠&f" in message
        replace all ":dizzy:" with "&e🥴&f" in message
        replace all ":woozy:" with "&e🥴&f" in message
        replace all ":sob:" with "😭&f" in message
        replace all ":qz1:" with "🤡&f" in message
        replace all ":clown:" with "🤡&f" in message
        replace all ":sparkles:" with "&e✨" in message
        replace all ":camera:" with "📷" in message
        replace all ":cashface:" with "&a🤑" in message
        replace all ":catface:" with "&6😸" in message
    if {emojichat} is false: # fix
    if message contains ":catface:" or ":cashface:" or ":)" or ":(" or "):" or "(:" or ":skull:" or ":kiss:" or ":heart:" or ":mad:" or ":dizzy:" or ":woozy:" or ":sob:" or ":qz1:" or ":clown:" or ":sparkles:" or ":camera:":
        send "Chat Emojis are Currently &c&lDisabled"


command /EmojiChat [<text>]:
    permission: skript.emoji.toggle
    trigger:
        if arg-1 is "Enable":
            set {emojiChat} to true
            send "(Personal) Chat Emojis have been &a&lEnabled"
            broadcast "(Server Wide) Chat emojis are now &a&lEnabled"
        if arg-1 is "Disable":
            set {emojiChat} to false
            send "(Personal) Chat Emojis have been &c&lDisabled"
            broadcast "(Server Wide) Chat Emojis are now &c&lDisabled"
            if arg-1 is not "Disable" or "Enabled":
                send "The only options are &a&lEnable&f/&c&lDisabled"
                send "awdsawd"